# 配置 Bash 语言支持
[[language]]
name = "bash"
scope = "source.sh"
file-types = ["sh"]
shebangs = ["sh", "bash"]
roots = [".git"]
indent = { tab-width = 4, unit = "    " }
language-servers = ["bash-language-server"]
auto-format = true

# 配置 Bash 语言服务器
[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]
