# bash
[[language]]
name = "bash"
scope = "source.sh"
file-types = ["sh"]
shebangs = ["sh", "bash"]
roots = [".git"]
indent = { tab-width = 4, unit = "    " }
language-servers = ["bash-language-server"]
auto-format = true

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

# js
[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]

[language.formatter]
command = "prettier"
args = ["--stdin-filepath", "%s"]

[[language]]
name = "lua"
auto-format = true
language-servers = ["lua-language-server"]

